name: DX

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      SFDX: /usr/local/lib/node_modules/sfdx-cli/bin/run

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install sfdx-cli
      run: npm install sfdx-cli --global
    - name: Run DX
      run: $SFDX --version
    - name: Decrypt Server Key
      run: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K ${{ secrets.KEY }} -iv ${{ secrets.IV }}
    - name: JWT Auth to Dev Hub
      run: $SFDX force:auth:jwt:grant --clientid ${{ secrets.CONSUMERKEY }} --jwtkeyfile assets/server.key --username ${{ secrets.USERNAME }} --setdefaultdevhubusername -a ${{ secrets.MYHUB }} -r ${{ secrets.DEVHUBURL }}
    - name: Create Scratch Org
      run: $SFDX force:org:create -v ${{ secrets.MYHUB }} -s -f config/project-scratch-def.json -a ${{ secrets.SORG }} --loglevel debug
    - name: Remove Server Key
      run: rm assets/server.key
    # - name: Install Lightning Testing Service
    #   run:  $SFDX force:lightning:test:install -t jasmine
    - name: Push Source
      run: $SFDX force:source:push -u ${{ secrets.SORG }}
    - name: Run Tests
      run: |
        mkdir -p ~/tests/apex
        $SFDX force:apex:test:run -u ${{ secrets.SORG }} -c -r human -d ~/tests/apex -w 9999  
    - name: Data Tree Import
      run: $SFDX force:data:tree:import -p data/plan1.json -u ${{ secrets.SORG }}
    - name: SOQL Query
      run: $SFDX force:data:soql:query -q "SELECT Id, Name FROM Account"
    - name: Pull Source
      run: $SFDX force:source:pull -u ${{ secrets.SORG }}
    - name: CleanUp
      run: |
        $SFDX force:org:delete -u ${{ secrets.SORG }} -p
        rm ~/tests/apex/*.txt ~/tests/apex/test-result-7*.json
        
